slice_name: ARR
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '2023-02-01 : '
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_g50s1k6ehmp_mq14gimju2s
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: ds
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_l69ee97pnv_m85q9ao901c
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: 'EXTRACT(DAY FROM ds) = 1 AND

      EXTRACT(MONTH FROM ds) IN (2,5,8,11)'
    subject: null
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 447
  datasource: 943__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: PLG
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      uuid: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: PLG
    optionName: metric_m3n4ky0iwv_1pz03419sxu
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: conversions
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: conversions
    optionName: metric_iqar399iweb_d2h7c5w16jw
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales_led
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: null
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: sales_led
    optionName: metric_26ob9f47zvu_b5yem6qytu
    sqlExpression: null
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 1000
  showTooltipTotal: true
  show_empty_columns: true
  show_legend: true
  slice_id: 3628
  sort_series_type: sum
  stack: Stack
  time_grain_sqla: P1D
  time_shift_color: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  xAxisLabelInterval: auto
  x_axis: ds
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 30
  y_axis_title_position: Left
query_context: '{"datasource":{"id":943,"type":"table"},"force":false,"queries":[{"filters":[{"col":"ds","op":"TEMPORAL_RANGE","val":"2023-02-01
  : "}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(EXTRACT(DAY FROM ds)
  = 1 AND\nEXTRACT(MONTH FROM ds) IN (2,5,8,11))"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"ds","label":"ds","expressionType":"SQL"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"PLG","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"PLG","optionName":"metric_m3n4ky0iwv_1pz03419sxu","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"conversions","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"conversions","optionName":"metric_iqar399iweb_d2h7c5w16jw","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"sales_led","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"sales_led","optionName":"metric_26ob9f47zvu_b5yem6qytu","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"PLG","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"PLG","optionName":"metric_m3n4ky0iwv_1pz03419sxu","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["ds"],"columns":[],"aggregates":{"PLG":{"operator":"mean"},"conversions":{"operator":"mean"},"sales_led":{"operator":"mean"__JINJA2_CLOSE__,"drop_missing_columns":false__JINJA2_CLOSE__,{"operation":"flatten"}]}],"form_data":{"datasource":"943__table","viz_type":"echarts_timeseries_bar","slice_id":3628,"x_axis":"ds","time_grain_sqla":"P1D","x_axis_sort_asc":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"PLG","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"PLG","optionName":"metric_m3n4ky0iwv_1pz03419sxu","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"conversions","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"conversions","optionName":"metric_iqar399iweb_d2h7c5w16jw","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"sales_led","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":null,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"sales_led","optionName":"metric_26ob9f47zvu_b5yem6qytu","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"2023-02-01
  : ","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_g50s1k6ehmp_mq14gimju2s","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"ds"},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_l69ee97pnv_m85q9ao901c","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"EXTRACT(DAY
  FROM ds) = 1 AND\nEXTRACT(MONTH FROM ds) IN (2,5,8,11)","subject":null}],"order_desc":true,"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"stack":"Stack","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[447],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b26ef548-4433-4c16-af02-e6e225a5897e
version: 1.0.0
dataset_uuid: 3800d084-0583-4c77-a273-48e421dfe040
tags: []
