slice_name: 'Cord: User Events over time'
description: null
certified_by: null
certification_details: null
viz_type: ag-grid-table
params:
  datasource: 138__table
  viz_type: ag-grid-table
  slice_id: 3245
  query_mode: aggregate
  groupby:
  - dttm
  - event_name
  time_grain_sqla: P1D
  temporal_columns_lookup:
    dttm: true
    dt: true
    team_created_dttm: true
    loaded_at: true
    last_accessed_at: true
    hs_company_db_created: true
    hs_company_last_activity_date: true
    uuid_ts: true
    original_timestamp: true
    received_at: true
    sent_at: true
    timestamp: true
  metrics:
  - users
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - notification_clicked
    - new_thread_started
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_1wc4q4j1xa7h_a6d05ts51r9
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: event_name
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_wdd33maecu_2c4lgyubrbg
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: dttm
  order_by_cols: []
  row_limit: 1000
  order_desc: true
  table_timestamp_format: smart_date
  include_search: true
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  table_state:
    columnOrder:
      orderedColIds:
      - dttm
      - event_name
      - users
    columnSizing:
      columnSizingModel:
      - colId: dttm
        flex: 1
        width: 198
      - colId: event_name
        flex: 1
        width: 199
      - colId: users
        flex: 1
        width: 198
    sort:
      sortModel:
      - colId: dttm
        sort: asc
    pagination:
      page: 0
      pageSize: 100
    aggregation:
      aggregationModel:
      - colId: users
        aggFunc: Metric total
    partialColumnState: true
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 92
query_context: '{"datasource":{"id":138,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_name","op":"IN","val":["notification_clicked","new_thread_started"]},{"col":"dttm","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"dttm","label":"dttm","expressionType":"SQL"},"event_name"],"metrics":["users"],"orderby":[["users",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"138__table","viz_type":"ag-grid-table","slice_id":3245,"query_mode":"aggregate","groupby":["dttm","event_name"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"dttm":true,"dt":true,"team_created_dttm":true,"loaded_at":true,"last_accessed_at":true,"hs_company_db_created":true,"hs_company_last_activity_date":true,"uuid_ts":true,"original_timestamp":true,"received_at":true,"sent_at":true,"timestamp":true},"metrics":["users"],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":["notification_clicked","new_thread_started"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_1wc4q4j1xa7h_a6d05ts51r9","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"event_name"},{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_wdd33maecu_2c4lgyubrbg","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"dttm"}],"order_by_cols":[],"row_limit":1000,"order_desc":true,"table_timestamp_format":"smart_date","include_search":true,"allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","table_state":{"columnOrder":{"orderedColIds":["dttm","event_name","users"]},"columnSizing":{"columnSizingModel":[{"colId":"dttm","flex":1,"width":198},{"colId":"event_name","flex":1,"width":199},{"colId":"users","flex":1,"width":198}]},"sort":{"sortModel":[{"colId":"dttm","sort":"asc"}]},"pagination":{"page":0,"pageSize":100},"aggregation":{"aggregationModel":[{"colId":"users","aggFunc":"Metric
  total"}]},"partialColumnState":true},"comparison_type":"values","extra_form_data":{},"dashboards":[92],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: da5735e5-f8fd-4cd1-8db7-ea9e949ab780
version: 1.0.0
dataset_uuid: 188ff56a-af45-4de3-b2ab-e851ef4e8612
tags: []
