slice_name: Time sync last fivetran/huspot sync
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 942__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    last_deal_sync: true
  all_columns:
  - last_deal_sync
  - hours_since_deal_sync
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: last_deal_sync
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  order_desc: true
  server_page_length: 10
  row_limit: 1000
  percent_metric_calculation: row_limit
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":942,"type":"table"},"force":false,"queries":[{"filters":[{"col":"last_deal_sync","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["last_deal_sync","hours_since_deal_sync"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"942__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"last_deal_sync":true},"all_columns":["last_deal_sync","hours_since_deal_sync"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"last_deal_sync","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"order_desc":true,"server_page_length":10,"row_limit":1000,"percent_metric_calculation":"row_limit","table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 10a45095-af7a-4af2-b9f0-eba8c33a199a
version: 1.0.0
dataset_uuid: 74654219-f320-43fd-b767-3e9af555726e
tags: []
